<<<<<<< HEAD
import "./globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
=======
import type { Metadata } from "next";
import "./globals.css"
import NavBar from "./components/nav"
import Footer from "./components/footer"
import LoggedInProvider from "./providers/loggedIn";

export const metadata: Metadata = {
  title: 'Avalie seu professor',
  description: 'Um site para os alunos avaliarem os professores da UnB.',
>>>>>>> 7a1a34135a18ef2c5667164769268ca54ef8c0c5
};

export default function RootLayout({
  children,
<<<<<<< HEAD
}: {
  children: React.ReactNode;
}) {
=======
}: Readonly<{
  children: React.ReactNode;
}>) {
>>>>>>> 7a1a34135a18ef2c5667164769268ca54ef8c0c5
  return (
    <html lang="pt-br">
      <LoggedInProvider>
        <body className="flex flex-col h-screen">
          <NavBar/>
          {children}
          <Footer/>
        </body>
      </LoggedInProvider>
    </html>
  );
}
